---
title: "UB13 -- Tutorium Mathe A WS19/20"
author: "A. Hanke"
date: "Tutorium: 03.02.2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aufgabe 1
- a: $a_nx^n = \sum_{n=0}^{\infty} x^{2n+1}$ mit $a_n = 1$.  
Konvergenzradius:$$ r = lim_{n \rightarrow \infty}\left| \frac{x^{2n + 2} }{x^{2n+1}} \right| = 1$$
Konvergenz radius $=1$
- b: $a_nx^n = \sum_{n = 0}^{\infty} (-1)^{n} 2^n x^n$  
  Konvergenzradius:$$ r = lim_{n \rightarrow \infty}
  \left| \frac{2^{n+1}x^{n+1}}{2^n x^n} \right| = |2x|$$
  Also gilt konvergenz bei: $|x|< 0.5$ und $r = 0.5$.
- c: $P(x) = \sum_{n =1}^{\infty} n x^n$  
  Konvergenzradius:$$r = \lim_{n \rightarrow \infty} \left| \frac{(n+1)x^{n+1}}{nx^n} \right| = \frac{n+1}{n} |x| <1 \Rightarrow r = 1$$
- d: $P(x) = \sum_{n = 1}^\infty \frac{x^n}{n^2}$  
  Konvergenzradius:$$r = \lim_{n\rightarrow \infty}
  \left| \frac{\frac{x^{n+1}}{(n+1)^2}}{\frac{x^n}{n^2}} \right| =
  \left|\frac{n^2 x^{n+1}}{(n+1)^2 x^n}\right|=
  \lim \left| \frac{n^2}{(n+1)^2} \right| |x| <1\rightarrow r = 1$$

# Aufgabe 2
### (a)
Reihe:
$$\frac{2}{3} + \frac{2}{3^2} + \frac{2}{3^3} + \dots = \sum_{n = 1}^\infty \frac{2}{3^n} = 2 \sum_{n = 1}^\infty \frac{1}{3^n}$$

Grenzwert:
\[
\begin{aligned}
    2 \sum_{n=1}^\infty \frac{1}{3^n} =& 2\underbrace{\sum_{n=0}^\infty \left( \frac{1}{3} \right)^n}_{
    |x|<1 \Rightarrow \sum_{n=0}^\infty x^n = \frac{1}{1-x}
    }- \left( \frac{1}{3} \right)^{n=0}\\
    =&2\frac{1}{1- \frac{1}{3}} -1\\
    =& 1
\end{aligned}
\]

### (b)
\[
    0.1+\frac{1}{2 !}(0.01)+\frac{1}{3 !}(0.001)+\ldots= \sum_{n=1}^\infty \frac{1}{n!} 0.1^n
\]
    Erkennen, das es sich um eine Taylor/Mac-Laurin Entwickluong handelt.
\[
    f(x) = \sum_{n=0}^\infty \frac{f^n(0)}{n!} x^n
\]
Daraus folgt:
\[
    \sum_{n=1}^\infty \frac{1}{n!} 0.1^n = \sum_{n=0}^\infty \frac{1}{n!} 0.1^n - 1 = e^{0.1} -1
\]


# Aufgabe 3

### (a)
\[f(x) = \frac{1}{\sqrt{x+1}} = \left( x+1 \right)^{\frac{-1}{2}}\quad \quad x = 0\]
Zunächst ableitungen bestimmen:
\[
\begin{array}{ccc}
    f'(x) =& - \frac{1}{2} (x+1)^{-\frac{3}{2}} & f'(0) = -\frac{1}{2}\\
    f''(x) =& - \frac{1}{2} \cdot -\frac{3}{2}(x+1)^{-\frac{5}{2}} & f''(0) = \frac{3}{4}\\
    f'''(x) =& - \frac{1}{2} \cdot -\frac{3}{2} \cdot -\frac{5}{2}(x+1)^{-\frac{7}{2}} & f'''(0) = -\frac{15}{8}
\end{array}
\]
Da $x_0 = 0$ gilt nun für die Taylor Näherung:
\[
    f(x) = \sum_{k=0}^3 \frac{f^k(0)}{k!} x^k
\]
Und somit hier:
\[
    f(x) = 1 - \frac{1}{2}x + \frac{3}{8} x^2 - \frac{5}{16} x^3
\]

### (b)
Bestimmen zunächst ableitungen um Reihe zu erkennen:
\[
\begin{array}{rl}
    f(x)&=(1-4 x)^{-1} \\ f^{\prime}(x)&=-4 \cdot -1(1-4 x)^{-2} \\
    f^{\prime \prime}(x)&=4 \cdot  -4 \cdot -2(1-4 x)^{-3} \\
    \Rightarrow f^{n}(x)&=(-1)^n(-4)^{n} n!(1-4 x)^{-n-1}=4^{n} n! (1-4 x)^{-n-1}\\
    \Rightarrow f^{n}(0) &= 4^n n!
\end{array}
\]

Konvergenzradius bestimmen (erinnere:
    $f(x)=\left(\sum_{n=0}^{\infty} \frac{f^{(n)}\left(x_{0}\right)}{n !}\left(x-x_{0}\right)^{n}\right)$):
\[
\begin{align}
    x_0 = 0
    \Rightarrow f(x) &= \sum_{n=0}^\infty 4^n x^n\\
    \text{Wurzelkriterium:}& \lim_{n\rightarrow \infty} 
    \sqrt[n]{|4^nx^n|}\\
    &= \left| 4x \right| < 1\\
    &\Rightarrow \text{Konvergenz für: } |x| < \frac{1}{4}\\
    \Rightarrow & r=\frac{1}{4}
\end{align}
\]

### (c)
Reihe erkennen:
\[
\begin{align}
    f(x)&=e^{1-x} \\
    &= ee^{-x} \\
    = e \sum_{n=0}^\infty \frac{(-x)^n}{n!}
\end{align}
\]
Konvergenzradius:
\[
\begin{align}
    \text{Quotienten:}& \lim_{n\rightarrow \infty} 
    \left| \frac{\frac{(-x)^{n+1}}{(n+1)!}}{\frac{(-x)^n}{n!}} \right|\\
    &=  \lim_{n\rightarrow \infty} \left| \frac{n!}{(n+1)!} -x \right|\\
    &= 0\\
    \Rightarrow & r=\infty
\end{align}
\]

# Aufgabe (4)

- a:
  $a = 2$  
  \[
  f(x) \sim a^4 + 4a^3 (x - a) = `r 2^4 + 4*2^3 * 0.001`
  \]
  Fehler: $`r 2.001^4 - (2^4 + 4*2^3 * 0.001)`$
- b:
  $a = 0$
  \[
  f(x) \sim \sin(a) + \cos(a) (x - a) = `r sin(0) + cos(0) * (0.02-0)`
  \]
  Fehler: $`r sin(0.02) - (sin(0) + cos(0) * (0.02-0))`$
- c:
  $a = 0$
  \[
  f(x) \sim \cos(a) + \sin(a) (x - a) = `r cos(0) + sin(0) * (0.03-0)`
  \]
  Fehler: $`r cos(0.03) - (cos(0) + sin(0) * (0.03-0))`$
- d:
  $a = 16$
  \[
  f(x) \sim  a^{\frac{1}{4}} + \frac{1}{4}a^{-\frac{3}{4}} (x - a) = `r 16^0.25 + 0.25*16^(-0.75) * (15.99- 16)`
  \]
  Fehler: $`r 15.99**0.25 - (16^0.25 + 0.25*16^(-0.75) * (15.99-16))`$
- e:
  $a = 1$
  \[
  f(x) \sim a^{-1}  - a^{-2} (x - a) = `r 1^(-1) - 1^(-2) * (0.98-1)`
  \]
  Fehler: $`r 1/0.98 - (1^(-1) - 1^(-2) * (0.98-1))`$
- f:
  $a = \pi$
  \[
  f(x) \sim \sin(a) + \cos(a) (x - a) = `r sin(pi) + cos(pi) * (3.14-pi)`
  \]
  Fehler: $`r sin(3.14) - (sin(pi) + cos(pi) * (3.14-pi))`$
